---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.selector.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /health
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
