replicaCount: 1
app:
  name: dougs-test
image:
  repository: dougs-test
  tag: 1.0.0
ingress:
  host: localhost
  name: dougs-test-ingress
service:
  port: 80
  targetPort: 80
  name: dougs-test-service
  type: NodePort
  selector:
    app: dougs-test

